openapi: 3.1.0
info:
  title: GeminiSpector API
  version: 1.0.0
  description: |
    API to evaluate text through Google Gemini. Returns structured scores.
servers:
  - url: https://geminispector.onrender.com
paths:
  /text/evaluate:
    post:
      summary: Evaluate text using Gemini
      operationId: evaluateText
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluateTextRequest'
      responses:
        '200':
          description: Successful evaluation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateTextResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    EvaluateTextRequest:
      type: object
      properties:
        text:
          type: string
          description: Text to evaluate
        criteria:
          type: array
          description: List of evaluation criteria
          items:
            type: string
      required:
        - text
    EvaluateTextResponse:
      type: object
      properties:
        correctness:
          type: number
          description: Correctness score (0-10)
        sources:
          type: array
          description: List of reference URLs
          items:
            type: string
        correction:
          type: string
          nullable: true
          description: Corrected text
        explanation:
          type: string
          nullable: true
          description: Why the correction was needed
      required:
        - correctness
        - sources
